apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osi-cards
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - osi-cards.com
    - www.osi-cards.com
    secretName: osi-cards-tls
  rules:
  - host: osi-cards.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: osi-cards
            port:
              number: 80
  - host: www.osi-cards.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: osi-cards
            port:
              number: 80


